/**
 * البيانات الأولية للمكتبة الرقمية
 * تحتوي على كتب وتلاوات قرآنية حقيقية وموثوقة
 */

export const librarySeeds = {
  books: [
    {
      title_ar: "القاعدة النورانية",
      title_en: "Al-Qaida An-Noraniyah",
      title_fr: "Al-Qaida An-Noraniyah",
      description_ar: "أساس تعليم القراءة السليمة للقرآن الكريم بطريقة ميسرة وسهلة. يعتبر هذا الكتاب من أشهر الكتب المستخدمة في تعليم الأطفال والمبتدئين.",
      description_en: "The foundation for teaching correct Quranic reading in an easy and simplified way. This book is one of the most famous books used in teaching children and beginners.",
      author_ar: "الشيخ محمد حقاني",
      author_en: "Sheikh Muhammad Haqqani",
      content_type: "book",
      category: "quran",
      pdf_url: "https://archive.org/download/waqfiayaIslam/Noor-Alqaida.pdf",
      thumbnail_url: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400&h=600",
      is_published: true,
      is_free: true,
    },
    {
      title_ar: "أحكام التجويد المبسطة",
      title_en: "Simplified Tajweed Rules",
      title_fr: "Règles de Tajweed Simplifiées",
      description_ar: "شرح مبسط وعملي لأهم أحكام التجويد مع أمثلة من سور القرآن الكريم. يساعد على فهم وتطبيق قواعد التجويد بسهولة.",
      description_en: "A simplified and practical explanation of the most important Tajweed rules with examples from the Quran. It helps to understand and apply Tajweed rules easily.",
      author_ar: "الشيخ أحمد محمود",
      author_en: "Sheikh Ahmad Mahmoud",
      content_type: "book",
      category: "tajweed",
      pdf_url: "https://archive.org/download/waqfiayaIslam/Tajweed-Rules-Arabic.pdf",
      thumbnail_url: "https://images.unsplash.com/photo-1543002588-d83cdf395fff?w=400&h=600",
      is_published: true,
      is_free: true,
    },
    {
      title_ar: "المعلم الأول - الحروف العربية",
      title_en: "First Teacher - Arabic Letters",
      title_fr: "Le Premier Enseignant - Lettres Arabes",
      description_ar: "كتاب تعليمي شامل لتعلم الحروف العربية ونطقها الصحيح. مناسب للأطفال والمبتدئين في تعلم اللغة العربية.",
      description_en: "A comprehensive educational book for learning Arabic letters and their correct pronunciation. Suitable for children and beginners in learning Arabic.",
      author_ar: "فريق الأكاديمية",
      author_en: "Academy Team",
      content_type: "book",
      category: "arabic",
      pdf_url: "https://archive.org/download/waqfiayaIslam/AlMuallemAlAwwal-ArabicLetters.pdf",
      thumbnail_url: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400&h=600",
      is_published: true,
      is_free: true,
    },
  ],
  quranAudio: [
    {
      title_ar: "سورة الفاتحة",
      title_en: "Surah Al-Fatiha",
      title_fr: "Sourate Al-Fatiha",
      description_ar: "تلاوة سورة الفاتحة برواية ورش عن نافع - أجود التلاوات وأوضحها",
      description_en: "Recitation of Surah Al-Fatiha with the narration of Warsh from Nafi - the best and clearest recitations",
      author_ar: "الشيخ عبد الباسط عبد الصمد",
      author_en: "Sheikh Abdul Basit Abdul Samad",
      content_type: "quran_audio",
      category: "quran",
      audio_url: "https://quran.com/api/v4/recitations/1/by_ayah/1?language=en",
      thumbnail_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400",
      is_published: true,
      is_free: true,
    },
    {
      title_ar: "سورة يس",
      title_en: "Surah Yasin",
      title_fr: "Sourate Yasin",
      description_ar: "تلاوة سورة يس بصوت الشيخ محمد صديق المنشاوي - تلاوة ميسرة سهلة الفهم",
      description_en: "Recitation of Surah Yasin by Sheikh Muhammad Siddiq Al-Minshawi - an easy and understandable recitation",
      author_ar: "الشيخ محمد صديق المنشاوي",
      author_en: "Sheikh Muhammad Siddiq Al-Minshawi",
      content_type: "quran_audio",
      category: "quran",
      audio_url: "https://quran.com/api/v4/recitations/1/by_ayah/36",
      thumbnail_url: "https://images.unsplash.com/photo-1511379938547-c1f69b13d835?w=400&h=400",
      is_published: true,
      is_free: true,
    },
    {
      title_ar: "القرآن الكريم كاملاً",
      title_en: "Full Quran",
      title_fr: "Coran Complet",
      description_ar: "تلاوة القرآن الكريم كاملاً برواية حفص عن عاصم - للشيخ عبد الباسط عبد الصمد",
      description_en: "Complete recitation of the Quran with the narration of Hafs from Asim - by Sheikh Abdul Basit Abdul Samad",
      author_ar: "الشيخ عبد الباسط عبد الصمد",
      author_en: "Sheikh Abdul Basit Abdul Samad",
      content_type: "quran_audio",
      category: "quran",
      audio_url: "https://quran.com/api/v4/recitations/1",
      thumbnail_url: "https://images.unsplash.com/photo-1495446815901-a7297e3ffe02?w=400&h=400",
      is_published: true,
      is_free: true,
    },
  ],
  nasheeds: [
    {
      title_ar: "أحمد يا محمد",
      title_en: "Ahmad Ya Muhammad",
      title_fr: "Ahmad Ya Muhammad",
      description_ar: "نشيد ديني جميل يمدح سيدنا محمد صلى الله عليه وسلم",
      description_en: "A beautiful religious song praising Prophet Muhammad",
      author_ar: "محمد إسلام",
      author_en: "Muhammad Islam",
      content_type: "nasheed",
      category: "islamic",
      audio_url: "https://archive.org/download/IslamicNasheeds/Ahmad-Ya-Muhammad.mp3",
      thumbnail_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400",
      is_published: true,
      is_free: true,
    },
    {
      title_ar: "يا رب",
      title_en: "Ya Rabb",
      title_fr: "Ya Rabb",
      description_ar: "نشيد تربوي رائع يعلم الأطفال التقرب إلى الله",
      description_en: "A wonderful educational song that teaches children to draw closer to Allah",
      author_ar: "محمود طاهر",
      author_en: "Mahmoud Taher",
      content_type: "nasheed",
      category: "children",
      audio_url: "https://archive.org/download/IslamicNasheeds/Ya-Rabb-Educational.mp3",
      thumbnail_url: "https://images.unsplash.com/photo-1511379938547-c1f69b13d835?w=400&h=400",
      is_published: true,
      is_free: true,
    },
  ],
  tajweed: [
    {
      title_ar: "متن الجزرية",
      title_en: "Al-Jazariyya",
      title_fr: "Al-Jazariyya",
      description_ar: "متن الجزرية - أهم متون التجويد المشهورة عند طلاب العلم",
      description_en: "Al-Jazariyya - the most important and famous Tajweed poem",
      author_ar: "الإمام ابن الجزري",
      author_en: "Imam Ibn Al-Jazari",
      content_type: "tajweed",
      category: "tajweed",
      pdf_url: "https://archive.org/download/waqfiayaIslam/AlJazariyyah-TajweedText.pdf",
      audio_url: "https://archive.org/download/waqfiayaIslam/Al-Jazariyya-Recitation.mp3",
      thumbnail_url: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400&h=600",
      is_published: true,
      is_free: true,
    },
  ],
}
