"use client"

import { useMemo, useState } from "react"
import { Plus, Save, Trash2 } from "lucide-react"
import { unitedStatesLandingConfig, type UnitedStatesPlan } from "@/lib/united-states-landing-config"

export function UnitedStatesLandingTab() {
  const [plans, setPlans] = useState<UnitedStatesPlan[]>(() => [...unitedStatesLandingConfig.plans])
  const [title, setTitle] = useState<string>(unitedStatesLandingConfig.seo.title)
  const [description, setDescription] = useState<string>(unitedStatesLandingConfig.seo.description)
  const [status, setStatus] = useState("")
  const update = (id: string, patch: Partial<UnitedStatesPlan>) => setPlans((current) => current.map((plan) => plan.id === id ? { ...plan, ...patch } : plan))
  const add = () => setPlans((current) => [...current, { id: `draft-${Date.now()}`, duration: 30, monthlySessions: 4, weeklySessions: 1, price: 0, name: "باقة جديدة", description: "وصف الباقة", features: ["ميزة جديدة"], visible: true }])
  const visiblePlans = useMemo(() => plans.filter((plan) => plan.visible), [plans])
  return <div className="space-y-6" dir="rtl">
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">صفحة الولايات المتحدة</h2><p className="mt-2 text-sm text-muted-foreground">إدارة محتوى صفحة تحفيظ القرآن للعائلات العربية في أمريكا.</p></div><button type="button" onClick={() => setStatus("تم حفظ التعديلات محلياً كمسودة.")} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 font-bold text-primary-foreground"><Save size={17} /> حفظ مسودة</button></div>{status && <p className="mt-4 rounded-lg bg-secondary p-3 text-sm" role="status">{status}</p>}</section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h3 className="text-lg font-bold">Hero وSEO</h3><div className="mt-4 grid gap-4"><label className="grid gap-2 text-sm font-semibold">عنوان SEO<input value={title} onChange={(event) => setTitle(event.target.value)} className="rounded-lg border border-border bg-background p-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold">الوصف التعريفي<textarea value={description} onChange={(event) => setDescription(event.target.value)} className="min-h-24 rounded-lg border border-border bg-background p-3 font-normal" /></label><p className="text-xs text-muted-foreground">المسار: /united-states · العملة: الدولار الأمريكي · رقم واتساب مرتبط بالإعدادات الحالية.</p></div></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">باقات تحفيظ القرآن بالدولار</h3><p className="mt-1 text-sm text-muted-foreground">يمكن تعديل الأسعار والنصوص أو إضافة وحذف الباقات من المسودة.</p></div><button type="button" onClick={add} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-bold"><Plus size={16} /> إضافة باقة</button></div><div className="mt-5 grid gap-4">{visiblePlans.map((plan) => <div key={plan.id} className="rounded-xl border border-border p-4"><div className="grid gap-3 md:grid-cols-6"><input aria-label="اسم الباقة" value={plan.name} onChange={(event) => update(plan.id, { name: event.target.value })} className="rounded-lg border border-border bg-background p-2 md:col-span-2" /><select aria-label="مدة الحصة" value={plan.duration} onChange={(event) => update(plan.id, { duration: Number(event.target.value) as UnitedStatesPlan["duration"] })} className="rounded-lg border border-border bg-background p-2"><option value="30">30 دقيقة</option><option value="40">40 دقيقة</option><option value="60">60 دقيقة</option></select><input aria-label="السعر بالدولار" type="number" value={plan.price} onChange={(event) => update(plan.id, { price: Number(event.target.value) })} className="rounded-lg border border-border bg-background p-2" /><input aria-label="عدد الحصص شهرياً" type="number" value={plan.monthlySessions} onChange={(event) => update(plan.id, { monthlySessions: Number(event.target.value) as UnitedStatesPlan["monthlySessions"] })} className="rounded-lg border border-border bg-background p-2" /><button type="button" aria-label="حذف الباقة" onClick={() => setPlans((current) => current.filter((item) => item.id !== plan.id))} className="inline-flex items-center justify-center rounded-lg border border-destructive/30 p-2 text-destructive"><Trash2 size={17} /></button></div><textarea aria-label="وصف الباقة" value={plan.description} onChange={(event) => update(plan.id, { description: event.target.value })} className="mt-3 min-h-20 w-full rounded-lg border border-border bg-background p-2" /></div>)}</div></section>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><h3 className="text-lg font-bold">المدن والمميزات والأسئلة الشائعة</h3><p className="mt-2 leading-7 text-muted-foreground">المدن المستهدفة: {unitedStatesLandingConfig.cities.join("، ")}.</p><p className="mt-2 text-sm text-muted-foreground">محتوى المميزات وFAQ ورسائل واتساب محفوظ في الإعدادات المنظّمة للصفحة وقابل للنقل إلى مصدر دائم لاحقاً دون تغيير قاعدة البيانات.</p></section>
  </div>
}
